Fixed typo in classes and outerclasses and added outerclasses to column and section fields
getgrav/grav-plugin-admin pull request #2424
Opened 2024-10-20 19:21 UTC by pmoreno-rodriguez

2024-12-23 16:52 UTC, pmoreno-rodriguez commented
Hi @rhukster

Regarding this pull request, I have modified the following to make it consistent across all Grav theme templates in the Admin plugin:

Fixed field_classes to field.classes for some field types.
Separated classes from outerclasses, adding a div block for the latter.
Added field.heading_classes to differentiate classes in the h1 tag from classes used in other blocks
I am still reviewing the use of classes in the rest of the Admin plugin templates. If you see these changes well, I will add the necessary help in Grav Learn Docs for the new attributes

2024-12-23 20:44 UTC, pmoreno-rodriguez commented
Ok. @rk

I think I've made too many commits on the same files, in two different pull requests, and maybe I should organize my Admin plugin repository, and make a single pull request with all the files I propose to modify. That way it would be clearer.

Right now, even I'm getting confused. 

Do you think I should close pull requests #2432 and #2424 to unify all the changes in a single pr?

2025-01-03 16:23 UTC, Karmalakas requested changes
It's up to Grav team, but I would not approve this PR 😔

2025-01-03 16:23 UTC, Karmalakas commented on themes/grav/templates/forms/field.html.twig
> +    <div class="form-field grid{% if vertical %} vertical{% endif %}{% if toggleable %} form-field-toggleable{% endif %} {{ field.classes }}">
This completely changes HTML of the field (same goes for section below) 🧐
The way I see it, it's a breaking change

2025-01-03 16:23 UTC, Karmalakas commented on themes/grav/templates/forms/fields/column/column.html.twig
> -{% extends "forms/field.html.twig" %}
Where did the column go? I don't see any replacement 👀

2025-01-03 16:43 UTC, pmoreno-rodriguez commented
> It's up to Grav team, but I would not approve this PR 😔

What do you recommend me?

2025-01-03 16:48 UTC, Karmalakas commented
> > It's up to Grav team, but I would not approve this PR 😔
> 
> What do you recommend me?

I can't really recommend much, because PR description is empty, and I don't understand why this change is actually needed in the first place 😕 I see in the comment you listed what you did, but what's the reason for this? 🤔

2025-01-03 16:48 UTC, pmoreno-rodriguez commented on themes/grav/templates/forms/fields/column/column.html.twig
> -{% extends "forms/field.html.twig" %}
You're right. That was a big mistake.

2025-01-03 16:54 UTC, pmoreno-rodriguez commented on themes/grav/templates/forms/field.html.twig
> +    <div class="form-field grid{% if vertical %} vertical{% endif %}{% if toggleable %} form-field-toggleable{% endif %} {{ field.classes }}">
There is no point in this line:
```
<div class="form-section {{ field.field_classes }} {{ field.outer_classes }}">
```
having field_classes and outer_classes applied to the same div block. Either apply outer_classes to a different block, which wraps the next one (my choice), or remove outer_classes from that div tag.

2025-01-03 16:58 UTC, pmoreno-rodriguez commented
> > What do you recommend me?
> 
> I can't really recommend much, because PR description is empty, and I don't understand why this change is actually needed in the first place 😕 I see in the comment you listed what you did, but what's the reason for this? 🤔

The PR is not well structured. I'm going to do it differently, with small PRs, each with its proposed changes.
The reason for these changes is to make the Grav documentation consistent with the code. In the [forms documentation](https://learn.getgrav.org/17/forms/forms/fields-available), you can see that `classes` and `outerclasses` are proposed as common attributes. In some Admin and Form plugin files, some of these attributes are missing or not well defined.

2025-01-03 17:16 UTC, Karmalakas commented on themes/grav/templates/forms/field.html.twig
> +    <div class="form-field grid{% if vertical %} vertical{% endif %}{% if toggleable %} form-field-toggleable{% endif %} {{ field.classes }}">
Imagine I have in my CSS:
```css
.form-field.grid.outer-class { color: red; }
```

Old HTML, which shows text in red:
```html
<div class="form-field grid {{ field.outerclasses }}"> ... </div>
```

New HTML, which doesn't show text in red any more:
```html
<div class="{{ outerclasses }}">
    <div class="form-field grid"> ... </div>
</div>
```

2025-01-03 18:02 UTC, pmoreno-rodriguez commented on themes/grav/templates/forms/field.html.twig
> +    <div class="form-field grid{% if vertical %} vertical{% endif %}{% if toggleable %} form-field-toggleable{% endif %} {{ field.classes }}">
I understand from what you put that in the blueprint you have put:
`outerclassses: outer-class`

Well, now imagine that you want to set the red color for each field inside the outerclasses block, that is, something like this:
```
<div class="{{ outerclasses }}">
<div class="form-field grid {{ field.classes }}"> ... </div>
</div>
```
Now your red text is applied to field.classes, and in outerclasses, for example, you could set a padding or a margin between the fields.

With the current code, this cannot be done.
Let me finish some changes and I will show you what I am telling you. I am modifying the Deliver theme and in it I am implementing some of these changes.

2025-01-03 21:28 UTC, pmoreno-rodriguez commented
I'm closing this PR to recreate it with corrections.

2025-01-03 21:28 UTC, closed without merging